version: "2"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "mariadb_data:/bitnami/mariadb"
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "magento_data:/bitnami/magento"
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - "elasticsearch_data:/bitnami/elasticsearch/data"
  laravel:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=bn_magento
      - DB_DATABASE=bitnami_laravel
    depends_on:
      - mariadb
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - "magento_data:/bitnami/laravel"
    privileged: true
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
  laravel_data:
    driver: local
